apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-privileged
  name: nginx-privileged
  namespace: staging
spec:
  containers:
  - image: nginx
    name: nginx-privileged
    resources: {}
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
