apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx:1.23.1-alpine
    name: nginx
    resources: {}
    securityContext:
      privileged: true
  initContainers:
  - image: node:18-alpine3.15
    name: init-nodejs
    resources: {}
    securityContext:
      privileged: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
